
package ve.com.cantv.iptv.bss.webservice.validatecustomeriptv.validatecustomeriptv;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ValidateCustomerIPTVFault", targetNamespace = "http://validatecustomeriptv.webservice.bss.iptv.cantv.com.ve/ValidateCustomerIPTV/")
public class ValidateCustomerIPTVFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ValidateCustomerIPTVFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ValidateCustomerIPTVFault_Exception(String message, ValidateCustomerIPTVFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ValidateCustomerIPTVFault_Exception(String message, ValidateCustomerIPTVFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ve.com.cantv.iptv.bss.webservice.validatecustomeriptv.validatecustomeriptv.ValidateCustomerIPTVFault
     */
    public ValidateCustomerIPTVFault getFaultInfo() {
        return faultInfo;
    }

}
