
package ve.com.cantv.iptv.bss.webservice.validatecustomeriptv.validatecustomeriptv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidateCustomerIPTV", targetNamespace = "http://validatecustomeriptv.webservice.bss.iptv.cantv.com.ve/ValidateCustomerIPTV/", wsdlLocation = "http://picprod04.cantv.com.ve:8080/mule/services/IPTV_0037/IPTV0037ValidarClienteIPTV?wsdl")
public class ValidateCustomerIPTV_Service
    extends Service
{

    private final static URL VALIDATECUSTOMERIPTV_WSDL_LOCATION;
    private final static WebServiceException VALIDATECUSTOMERIPTV_EXCEPTION;
    private final static QName VALIDATECUSTOMERIPTV_QNAME = new QName("http://validatecustomeriptv.webservice.bss.iptv.cantv.com.ve/ValidateCustomerIPTV/", "ValidateCustomerIPTV");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://picprod04.cantv.com.ve:8080/mule/services/IPTV_0037/IPTV0037ValidarClienteIPTV?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDATECUSTOMERIPTV_WSDL_LOCATION = url;
        VALIDATECUSTOMERIPTV_EXCEPTION = e;
    }

    public ValidateCustomerIPTV_Service() {
        super(__getWsdlLocation(), VALIDATECUSTOMERIPTV_QNAME);
    }

    public ValidateCustomerIPTV_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDATECUSTOMERIPTV_QNAME);
    }

    public ValidateCustomerIPTV_Service(URL wsdlLocation) {
        super(wsdlLocation, VALIDATECUSTOMERIPTV_QNAME);
    }

    public ValidateCustomerIPTV_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDATECUSTOMERIPTV_QNAME);
    }

    public ValidateCustomerIPTV_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidateCustomerIPTV_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ValidateCustomerIPTV
     */
    @WebEndpoint(name = "ValidateCustomerIPTVSOAP")
    public ValidateCustomerIPTV getValidateCustomerIPTVSOAP() {
        return super.getPort(new QName("http://validatecustomeriptv.webservice.bss.iptv.cantv.com.ve/ValidateCustomerIPTV/", "ValidateCustomerIPTVSOAP"), ValidateCustomerIPTV.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidateCustomerIPTV
     */
    @WebEndpoint(name = "ValidateCustomerIPTVSOAP")
    public ValidateCustomerIPTV getValidateCustomerIPTVSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://validatecustomeriptv.webservice.bss.iptv.cantv.com.ve/ValidateCustomerIPTV/", "ValidateCustomerIPTVSOAP"), ValidateCustomerIPTV.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDATECUSTOMERIPTV_EXCEPTION!= null) {
            throw VALIDATECUSTOMERIPTV_EXCEPTION;
        }
        return VALIDATECUSTOMERIPTV_WSDL_LOCATION;
    }

}
