
package ve.com.cantv.iptv.bss.webservice.validatecustomeriptv.validatecustomeriptv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ValidateCustomerIPTV", targetNamespace = "http://validatecustomeriptv.webservice.bss.iptv.cantv.com.ve/ValidateCustomerIPTV/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidateCustomerIPTV {


    /**
     * 
     * @param idAccount
     * @param telephoneLine
     * @return
     *     returns boolean
     * @throws ValidateCustomerIPTVFault_Exception
     */
    @WebMethod(operationName = "ValidateCustomerIPTV", action = "http://validatecustomeriptv.webservice.bss.iptv.cantv.com.ve/ValidateCustomerIPTV/ValidateCustomerIPTV")
    @WebResult(name = "isCustomer", targetNamespace = "http://validatecustomeriptv.webservice.bss.iptv.cantv.com.ve/ValidateCustomerIPTV/")
    @RequestWrapper(localName = "ValidateCustomerIPTV", targetNamespace = "http://validatecustomeriptv.webservice.bss.iptv.cantv.com.ve/ValidateCustomerIPTV/", className = "ve.com.cantv.iptv.bss.webservice.validatecustomeriptv.validatecustomeriptv.ValidateCustomerIPTVInput")
    @ResponseWrapper(localName = "ValidateCustomerIPTVResponse", targetNamespace = "http://validatecustomeriptv.webservice.bss.iptv.cantv.com.ve/ValidateCustomerIPTV/", className = "ve.com.cantv.iptv.bss.webservice.validatecustomeriptv.validatecustomeriptv.ValidateCustomerIPTVOutput")
    public boolean validateCustomerIPTV(
        @WebParam(name = "idAccount", targetNamespace = "http://validatecustomeriptv.webservice.bss.iptv.cantv.com.ve/ValidateCustomerIPTV/")
        String idAccount,
        @WebParam(name = "telephoneLine", targetNamespace = "http://validatecustomeriptv.webservice.bss.iptv.cantv.com.ve/ValidateCustomerIPTV/")
        TelephoneLine telephoneLine)
        throws ValidateCustomerIPTVFault_Exception
    ;

}
